### PR TITLE
Pass through `--verbose` option to to git

### PR DESCRIPTION
**Pull request by smith**
Wrap the calls to `git` in an `execGit` function which adds `git ` to the front of the string and `--verbose` to the end (if `--verbose` was passed into backport.) and adds the `cwd` option.

### CODE REVIEW

**Comment by sqren** [comment]
Thanks @smith and sorry for the slow response. I just tried it out and ran into this error:
```
Command failed: git remote rm origin --verbose
```

It seems that not all git commands accept the `--verbose` flag?

**Comment by smith** [comment]
> Thanks @smith and sorry for the slow response. I just tried it out and ran into this error:
>
>     Command failed: git remote rm origin --verbose
> It seems that not all git commands accept the --verbose flag?

@sqren It seems they do accept it but the order matters.

So `git remote --verbose add origin git@github.com:sqren/backport.git` works but `git remote add origin git@github.com:sqren/backport.git --verbose` does not.

One way to handle this might be by changing the signature so the subcommand was a separate argument:

```
await execGit('commit', `--no-edit${noVerify}`, options);
```

Then we could always do `git ${subcommand} --verbose ${args}`. 

What do you think?

**Comment by sqren** [comment]
Hmm.. I'm wondering whether the `verbose` flag is worth it. What did you need it for?

**Comment by smith** [comment]
> What did you need it for?

It was failing to run on a new checkout, and passing `--verbose` didn't show any extra output from git. I had to copy/paste and run the git commands manually to see what was going on.

**Pull request closed without merging**
