### PR TITLE
Add option `sourceBranch`

### LINKED ISSUE #158: Cannot read property 'target' of null
I've probably misconfigured something, but when I simply run `backport --verbose` it fails with:

```
✖ Loading commits...
TypeError: Cannot read property 'target' of null
    at Object.fetchCommitsByAuthor (/Users/rkorving/Projects/redacted/node_modules/backport/dist/services/github/fetchCommitsByAuthor.js:95:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```
which translates to https://github.com/sqren/backport/blob/2a100ccfe1c339ead0f3c985e920e19bcd4d11f3/src/services/github/fetchCommitsByAuthor.ts#L108

When I look in the verbose log, the last steps I see are:

```
2019-10-08T07:56:48.850Z verbose: {
  "repoOwner": "redacted-but-correct",
  "repoName": "redacted-but-correct",
  "commitsCount": 10,
  "authorId": "redacted-but-some-correct-looking-hash",
  "historyPath": null
}
2019-10-08T07:56:49.303Z verbose: {
  "data": {
    "repository": {
      "ref": null
    }
  }
}
```

I use github.com, a private repo, and I know I have commits in its history.
I enabled these scopes when creating a token for it:

image

My project's `.backportrc.json` file:

```json
{
  "upstream": "myorg/myrepo",
  "branches": ["v0-master"],
  "all": true,
  "fork": true,
  "multipleCommits": true,
  "multipleBranches": true,
  "labels": ["backport"]
}
```

(I've tried with `"all": false` as well, but same result)

Backport v4.7.3.

### LINKED ISSUE #162: Hangs after creating the pull-request
Running `backport` and selecting the commits and branch interactively hangs after the pull-request have been created. I have to <kbd>ctrl+c</kbd> in order to continue.

My `config.json` only has `accessToken` and `username` and the `backport.log` file ends with `Adding label 'backport' to #8779`

### PR DESCRIPTION
**Pull request by sqren**
Closes #158
Closes #162

By default the list of commits will be sourced from the repository's default branch (mostly "master"). Use `sourceBranch` to list and backport commits from other branches than the default.

Configuration:
```json
{
  "sourceBranch": "7.x"
}
```

CLI: `--sourceBranch 7.x`

### CODE REVIEW

**Comment by sqren** [comment]
Releases as beta under `4.8.0-beta.0`. Can be installed with 
`yarn global add backport@beta` or `npm install -g backport@beta`

**Comment by ronkorving** [comment]
Fantastic! I will test this soon. Just an additional feature request though... Could we add the ability to interactively select a source branch (rather than using the default branch)?

**Comment by sqren** [comment]
> Fantastic! Worked beautifully!

Great to hear! Then I'll merge this shortly.

> Could we add the ability to interactively select a source branch (rather than using the default branch)?

I'm looking into this. I think for 95% of use cases people want to source commits from the default branch so they don't want to select "master" in a list every time. It could however be enabled as a config setting `showSourceBranchOptions: true` or something like it.

**Comment by ronkorving** [comment]
I think something like that makes sense. As you say, most people will just have a single source branch and the interactive option would just get in the way. An option would be good.

**Comment by sqren** [comment]
Released in [v4.8.0](https://github.com/sqren/backport/releases/tag/v4.8.0)

**Pull request merged**
