### PR TITLE
print the repo path on conflicts

### LINKED ISSUE #193: Backport repo directory is no longer printed on conflicts.
When I get conflicts in a backport I like to open a new VSCode window with the backport repo, so having the path to the repo printed was quite convenient. Now I need a little more precision to pull the repo path from the beginning of the file paths that are printed... It's a tiny QOL improvement, but it would be nice if the tool could print the path to the repo separately.

### PR DESCRIPTION
**Pull request by spalger**
Closes #193 

Prints the repo path before the files which are conflicting to make it easier to open the entire repo when desired.

### CODE REVIEW

**Comment by sqren** [comment]
Great, thanks! 
Can you do me a favor and update the snapshots? `yarn test -u`

**Comment by spalger** [comment]
You got it

**Comment by spalger** [comment]
Hmm, I see the same yargs errors on master

**Comment by sqren** [comment]
Yeah, it's because I'm using environment variables on travis and they are not available to contributors. 
The env variable is defined in my project settings: https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

**Comment by sqren** [comment]
I tried cleared cache and restarting the build but no luck. I want something like `retest` from Kibana...

**Comment by sqren** [comment]
Released in [5.4.2](https://www.npmjs.com/package/backport/v/5.4.2)

**Pull request merged**
