### PR TITLE
Feature: Add support for merge commits

### LINKED ISSUE #257: Backport commits in PR instead of merge commit
Currently when one runs
```
backport --pr 123
```
it seems that the tool searches for the merge commit that merged PR 123 into the master branch and then (I assume) it backports that merge commit.

This approach has two drawbacks:
1. It's only possible to backport PRs that have already been merged
2. It (presumably) does not allow for an easy way to backport the individual commits of a PR

To 1): We have a few CI runs that take a while to complete and sometimes I already know that I want to backport a PR before these checks have completed (and thus before we have merged the PR). In that case it'd be nice if I could already create the backport PR in order to give its checks a bit of a headstart so I don't have to wait that long for them to complete after having merged the original PR.

To 2): We don't backport merge commits. Instead we cherry-pick the commits of a particular PR on the backport branch and then create a PR from that. It would be nice if there was an easy way to automate this process using the `backport` tool. (If that is already possible, please let me know how)

### PR DESCRIPTION
**Pull request by sqren**
- Feature: Improve support for merge commits (Closes #257)
 - Fix: Fix bug where backport would fail if no .backportrc.json file existed

### CODE REVIEW

**Comment by Krzmbrzl** [comment]
Okay, I forgot how to make use of this feature and I can't seem to get it working anymore xD

Using the `--pr` option only seems to backport the first commit of that PR for me. Is there an additional CLI option that is intended for this feature? :see_no_evil:

**Comment by sqren** [comment]
@Krzmbrzl `--pr` option should be all that's needed. What version are you using? You need minimum 7.2.

As far as I can tell, it works as it should. Take a look at this dummy repo: https://github.com/backport-org/different-merge-strategies.

Try cloning it and then run

```
backport --repo backport-org/different-merge-strategies --branch 7.x --pr 9
```

Then you should see that it backports all commits from the source pull request. I did it [here](https://github.com/backport-org/different-merge-strategies/pull/12).

I might have missed an edge case so I'd love to see a reproducable case in a demo repo like the one above.

**Comment by Krzmbrzl** [comment]
Hm okay. Could it be related to the fact that I was seeing a merge conflict during the cherry-pick of that very first commit? Could that have thrown off the following logic?

I did encounter the issue while trying to backport https://github.com/mumble-voip/mumble/pull/5641 to https://github.com/mumble-voip/mumble/tree/1.4.x, though at commit [3960373d98f9226b73e947abc582e0e4e4ae5936](https://github.com/mumble-voip/mumble/tree/3960373d98f9226b73e947abc582e0e4e4ae5936).

**Comment by sqren** [comment]
Hi @Krzmbrzl 

Thanks for making me aware of this problem. I just confirmed this is indeed a problem when conflicts occur.

The pull requests is expected to have 8 commits like [here](https://github.com/backport-org/different-merge-strategies/pull/12/commits). But if a conflict occurs in the first commit, it omits the rest like [here](https://github.com/backport-org/different-merge-strategies/pull/13/commits).

I'll look into a fix.

**Comment by Krzmbrzl** [comment]
> I just confirmed this is indeed a problem when conflicts occur.

Aha - so it was not me doing something silly - that's good :D 

> I'll look into a fix.

Thanks! :+1:

**Comment by sqren** [comment]
@Krzmbrzl I've made a fix and released it in v8.4.1. Please let me know if it works for you if you have time.

**Comment by Krzmbrzl** [comment]
So I've been using the new version for a bit now and while I have yet to use it on a PR that causes a merge conflict, I now constantly keep running into issues where backlog "crashes" and in the logs there is always a message such as 
```
{"level":"error","message":"runSequentially failed Code: 128, Args: \"rev-list -1 --merges e93d486ba6f7504eb08b94befcfc9a07c4fc5aae~1..e93d486ba6f7504eb08b94befcfc9a07c4fc5aae\", Message: fatal: ambiguous argument 'e93d486ba6f7504eb08b94befcfc9a07c4fc5aae~1..e93d486ba6f7504eb08b94befcfc9a07c4fc5aae': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'","metadata":{"context":{"cmdArgs":["rev-list","-1","--merges","e93d486ba6f7504eb08b94befcfc9a07c4fc5aae~1..e93d486ba6f7504eb08b94befcfc9a07c4fc5aae"],"code":128,"stderr":"fatal: ambiguous argument 'e93d486ba6f7504eb08b94befcfc9a07c4fc5aae~1..e93d486ba6f7504eb08b94befcfc9a07c4fc5aae': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n","stdout":""},"name":"SpawnError","stack":"SpawnError: Code: 128, Args: \"rev-list -1 --merges e93d486ba6f7504eb08b94befcfc9a07c4fc5aae~1..e93d486ba6f7504eb08b94befcfc9a07c4fc5aae\", Message: fatal: ambiguous argument 'e93d486ba6f7504eb08b94befcfc9a07c4fc5aae~1..e93d486ba6f7504eb08b94befcfc9a07c4fc5aae': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/backport/dist/lib/child-process-promisified.js:37:29)\n    at ChildProcess.emit (node:events:526:28)\n    at maybeClose (node:internal/child_process:1092:16)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)"},"timestamp":"2022-05-18 09:43:06"}
```
I'm not sure if this is related to the latest changes though. This is backlog's output when this happens
```
$ backport --pr 5677
? Select pull request Merge PR #5677: CHANGE(client): Disable RNNoise by default
? Select branch 1.4.x

Backporting to 1.4.x:
✔ Pulling latest changes
An unhandled error occurred while backporting commit. Please see the logs for details
```

Whenever this happens I have to delete `.backport/repositories/<theRepo>` and then explicitly fetch the latest commits from the upstream master branch.

**Comment by Krzmbrzl** [comment]
Note: Just after I wrote this I did encounter a backport with merge conflicts and it seems to work as expected :+1:

**Comment by sqren** [comment]
> I now constantly keep running into issues where backlog "crashes"

@Krzmbrzl Thanks for the heads up! I was not aware of this problem until you pointed it out. I have [a fixed](https://github.com/sqren/backport/pull/370) ready and will merge and release it sometime Thursday.

**Comment by sqren** [comment]
The fix is released in 8.4.2.

**Comment by Krzmbrzl** [comment]
Can confirm that everything seems to be working smoothly again. Thank you! :+1:

**Pull request merged**
